# Font
font_family Maple Mono NF
font_size 15

# Window
window_padding_width 14
hide_window_decorations titlebar-only
placement_strategy center
confirm_os_window_close 0
active_border_color #00ff00

# Minimal Tab bar styling
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# Move to the beginning of the line
map super+left send_text all \x01

# Move to the end of the line
map super+right send_text all \x05

# Delete all behind cursor
map super+backspace send_text all \x15

# Delete word behind cursor
map alt+backspace send_text all \x1b\x7f

# New line and not submit
map shift+enter send_text all \n
