font_family Maple Mono NF
font_size 15

# Move to the beginning of the line
map super+left send_text all \x01

# Move to the end of the line
map super+right send_text all \x05

# Delete all behind cursor
map super+backspace send_text all \x15

# Delete word behind cursor
map alt+backspace send_text all \x1b\x7f

# New line and not submit
map shift+enter send_text all \n
