background #FFFBEF
foreground #5C6A72
cursor #F57D26
cursor_text_color #FFFBEF
selection_background #F0F2D4
selection_foreground #5C6A72

color0 #5C6A72
color1 #F85552
color2 #8DA101
color3 #DFA000
color4 #3A94C5
color5 #DF69BA
color6 #35A77C
color7 #EDEADA
color8 #5C6A72
color9 #F85552
color10 #8DA101
color11 #DFA000
color12 #3A94C5
color13 #DF69BA
color14 #35A77C
color15 #EDEADA
